#!/usr/bin/env php
<?php

chdir(realpath(__DIR__));

require_once __DIR__ . '/app/bootstrap/_generated.php';

global $app;

$commands = new \Naga\Core\Config\ConfigBag($app->fileSystem(), new \Naga\Core\Debug\Log\CommandLineLogger());
$commands->copyFrom(['commands' => [
	'update' => new \Naga\Core\Cli\Commands\Update(),
]]);
$commands->mergeWith($app->config('cli')->toArray());

$commandLine = new \Naga\Core\Cli\CommandLine($commands);

array_shift($argv);

if (!$argv)
	exit("Please specify a command!\n");

$commandName = array_shift($argv);
$commandLine->executeCommand($commandName, $argv);