#!/usr/bin/env php
<?php

chdir(realpath(__DIR__));

// checking whether generated bootstrap file exists
$bootstrapPath = __DIR__ . '/app/bootstrap/_generated.php';
if (file_exists($bootstrapPath))
	require_once $bootstrapPath;
else
	require_once __DIR__ . '/app/bootstrap.php';

$commands = new \Naga\Core\Config\ConfigBag($app->fileSystem(), new \Naga\Core\Debug\Log\CommandLineLogger());
$commands->copyFrom(['commands' => [
	'update' => new \Naga\Core\Cli\Commands\Update(),
]]);
$commands->mergeWith($app->config('cli')->toArray());

$commandLine = new \Naga\Core\Cli\CommandLine($commands);

array_shift($argv);

if (!$argv)
{
	$commandLine->error("Please specify a command!");
	$commandLine->dumpCommands();
	exit;
}

$commandName = array_shift($argv);
$commandLine->executeCommand($commandName, $argv);